

services:
  visionsearch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${user}
        userid: ${userid}
        group: ${group}
        groupid: ${groupid}
    image: tannousgeagea/visionsearch:latest
    container_name: visionsearch-core
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/home/appuser/src
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: visionsearch-db
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: