

services:
  visionsearch:
    build:
      context: .
      dockerfile: Dockerfile
    image: tannousgeagea/visionsearch:latest
    container_name: visionsearch-core
    env_file: .env
    volumes:
      - .:/home/appuser/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: visionsearch-db
    env_file: .env
    environment:
      POSTGRES_DB: visiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: