name: Auto Tag Version

on:
  push:
    branches:
      - main

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get-latest-tag
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1` || echo "0.0.0")
          echo "Latest tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Determine bump type
        id: bump-type
        run: |
          COMMITS=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMITS"

          if echo "$COMMITS" | grep -qiE "^feat:"; then
            echo "BUMP=minor" >> $GITHUB_ENV
          else
            echo "BUMP=patch" >> $GITHUB_ENV
          fi

      - name: Increment version
        id: increment-tag
        run: |
          VERSION=${{ env.TAG }}
          VERSION=${VERSION#v}  # remove v prefix if exists

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          if [ "${{ env.BUMP }}" = "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEW_TAG="$MAJOR.$MINOR.$PATCH"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New version: $NEW_TAG"

      - name: Create new tag
        run: |
          git tag -a "$NEW_TAG" -m "Release $NEW_TAG"
          git push origin "$NEW_TAG"
